apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}-worker
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.worker.additionalExposedPorts }}
    - port: {{ $value.servicePort }}
      name: {{ $value.name }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
    {{- end }}
  selector:
    app: {{ template "trino.name" . }}
    release: {{ .Release.Name }}
    component: worker
